name: Weather App CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4.2.0
        with:
          global-json-file: global.json

      - name: Set up Node.js
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 22.x
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Prettier Check
        run: npm run pcheck

      - name: Run Tests
        run: npm run tests

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: weather-app
          path: dist/
